export const SHOP_ROUTE = '/'
export const ADMIN_ROUTE = '/admin'
export const REGISTER_ROUTE = '/register'
export const LOGIN_ROUTE = '/login'
export const ITEM_ROUTE = '/item'
export const BASKET_ROUTE = '/basket'